CREATE TABLE BALANCE(
    USERID VARCHAR ,
    USERBALANCE INTEGER
);

CREATE TABLE RESERVED(
    USERID VARCHAR ,
    SERVICEID VARCHAR ,
    ORDERID VARCHAR,
    SUM INTEGER
);

CREATE TABLE FINISHED(
    USERID VARCHAR ,
    SERVICEID VARCHAR ,
    ORDERID VARCHAR,
    SUM INTEGER
);