CREATE TABLE BALANCE(
    USERID BIGINT ,
    USERBALANCE REAL
);

CREATE TABLE RESERVED(
    USERID BIGINT ,
    SERVICEID BIGINT ,
    ORDERID BIGINT,
    SUM REAL
);

CREATE TABLE FINISHED(
    USERID BIGINT ,
    SERVICEID BIGINT ,
    ORDERID BIGINT,
    SUM REAL
);