version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "avitotest"
      POSTGRES_USER: "avitotestuser"
      POSTGRES_PASSWORD: "avitotestpass"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"