version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "avitotest"
      POSTGRES_USER: "avitotestuser"
      POSTGRES_PASSWORD: "avitotestpass"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  server:
    build: server/
    command:
      - ./main
    ports:
      - "8080:8080"
    #network_mode: host
    depends_on:
      - postgres
